JobFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('JobFinderWeb.api.urls', namespace='JobApi')),
    path('', include('JobFinderWeb.urls', namespace='JobFinderWeb')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JobFinderWeb/api/urls.py
from django.urls import path
from rest_framework.generics import CreateAPIView
from .views import (JobApi,
                    JobListApi,
                    CompanyApi,
                    CompanyListApi,
                    CompanyJobsApi,
                    CreateCompanyApi,
                    NewJobApi,
                    GetResumeeListApi,
                    SeekerListApi,
                    SeekerDetailApi,
                    GetSeekerResumeeListApi,
                    ResumeeDetailApi,
                    CreateResumeeApi,
                    ApplicantListApi,
                    NewApplicationApi
                    )
from JobFinderWeb.models import Job
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls

schema_view = get_swagger_view(title='JobFinder Api')

app_name = 'JobApi'
urlpatterns = [
    # path('jobs', JobListApi.as_view(), name='joblist'),
    path('login', obtain_jwt_token, name='api-login'),
    path('job/<slug>', JobApi.as_view(), name='jobdetail'),
    path('jobs/', JobListApi.as_view(), name='listjob'),
    path('company/<slug>', CompanyApi.as_view(), name='companyDetail'),
    path('companies/', CompanyListApi.as_view(), name='companyList'),
    path('<slug>/jobs/', CompanyJobsApi.as_view(), name='companyJobList'),
    path('newcompany/', CreateCompanyApi.as_view(), name='newcompany'),
    path('newjob/', NewJobApi.as_view(), name='newjob'),
    path('resumee/', GetResumeeListApi, name='resumeeList'),
    path('resumee/<slug>', ResumeeDetailApi.as_view(), name='resumeeDetail'),
    path('<seeker>/resumee/', GetSeekerResumeeListApi.as_view(),
         name='seekerResumeeList'),
    path('seeker/', SeekerListApi.as_view(), name='seeker'),

    path('newresumee/', CreateResumeeApi.as_view(), name='newresumee'),
    path('seeker/<pk>', SeekerDetailApi.as_view(), name='seekerdetail'),
    path('newapplication/', NewApplicationApi.as_view(), name='newapplication'),
    path('<companyslug>/applicant/', ApplicantListApi.as_view(), name='applicant'),
    path('swagger-docs/', schema_view),
    path('docs/', include_docs_urls(title='JobFinder Api')),
]

JobFinderWeb/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (SeekerProfileView,
                    ProviderProfileView,
                    loginView, 
                    logout, 
                    SignUp, 
                    NewCompany,
                    CompanyDetailView,
                    NewJob,JobDetailView, 
                    CompanyListView,
                    UpdateCompany,
                    CompanyJobList,
                    UpdateJob,
                    DeleteCompany,
                    DeleteJob,
                    JobListView,
                    # NewResumee,
                    ResummeCreateView,
                    ResumeeDetail,
                    NewApplication,
                    JobCandidate,
                    ResumeeUpdateView
                    )

from django.contrib.auth import views as auth_views



app_name = 'JobFinderWeb'

urlpatterns = [
    path('', TemplateView.as_view(template_name='JobFinderWeb/home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='JobFinderWeb/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='JobFinderWeb/contact.html'), name='contact'),
    path('faq/', TemplateView.as_view(template_name='JobFinderWeb/faq.html'), name='faq'),
    path('register/', SignUp, name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='JobFinderWeb/login.html'), name='login'),
    path('login/', loginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('passwordreset/', TemplateView.as_view(template_name='JobFinderWeb/forgotpassword.html'), name='forgotpassword'),
    path('seeker/<str:username>/', SeekerProfileView.as_view(), name='jobseekerprofile'),
    path('provider/addcompany/', NewCompany.as_view(), name='newcompany'),
    path('<slug>/updatecompany/', UpdateCompany.as_view(), name='updatecompany'),
    path('<slug>/deletecompany/', DeleteCompany, name='deletecompany'),
    path('<slug>/deletejob/', DeleteJob, name='deletejob'),
    path('<slug>/updatejob/', UpdateJob.as_view(), name='updatejob'),
    path('<username>/jobs/', CompanyJobList.as_view(), name='companyjobs'),
    path('provider/addjob/', NewJob.as_view(), name='newjob'),
    path('provider/<str:username>/', ProviderProfileView.as_view(), name='jobproviderprofile'),
    path('company/<slug>/', CompanyDetailView.as_view(), name='companydetail'),


    path('companies/', CompanyListView.as_view(), name='companylist'),
    path('companies/<slug>/', CompanyListView.as_view(), name='companylist'),
    # path('companies/<slug>/<location>/', CompanyListView.as_view(), name='companylist'),
    # path('companies/<slug>/<location>/<kword>/', CompanyListView.as_view(), name='companylist'),
    path('joblisting/<slug>/', JobListView.as_view(), name='joblist'),
    path('job/<slug>/', JobDetailView.as_view(), name='jobdetail'),


    # job seeker urls section
    path('newresumee/', ResummeCreateView.as_view(), name='newresumee'),
    path('resumee/<slug>/', ResumeeDetail.as_view(), name='resumeedetail'),
    path('updateresumee/<slug>/', ResumeeUpdateView.as_view(), name='resumeupdate'),
    path('job/application/<jobslug>', NewApplication.as_view(), name='newapplication'),
    path('job/applicant/<jobslug>', JobCandidate.as_view(), name='applicants'),
    
]

JobFinderWeb/forms.py
from django import forms
from .validators import username_validate

from django.forms.models import inlineformset_factory

from .models import Seeker,Education,Experience,Skill,Provider,Company,Job,Resumee,Application,Identity,CustomJobApplication


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'placeholder':'Username'}))
    firstname = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'First Name'}))
    lastname = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Last Name'}))
    email = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))

class LoginForm(forms.Form):
    username = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'placeholder':'Username'}), validators=[username_validate])
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ('provider',)
        fields = '__all__'


class CustomApplicationForm(forms.ModelForm):
    name = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'class':'form-control input-lg','placeholder':'Name'}))

    email = forms.CharField(max_length=120,
        widget=forms.TextInput(attrs={'class':'form-control input-lg','placeholder':'Email'})) 
    
    message = forms.CharField(widget= forms.Textarea(attrs={'class':'form-control','placeholder':'Message', 'rows':'7'}))

    class Meta:
        model = CustomJobApplication
        exclude = ('application',)
        fields = '__all__'


class JobForm(forms.ModelForm):
    Company = forms.ModelChoiceField(queryset = Company.objects.all(), widget=forms.Select(attrs={'class':'form-control selectpicker'}))

    class Meta:
        model = Job
        exclude = ('slug',)
        fields = '__all__'
 
    def __init__(self, user=None, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)
        self.fields['Company'] = forms.ModelChoiceField(queryset = Company.objects.filter(provider = user, IsActive=True), widget=forms.Select(attrs={'class':'form-control selectpicker'}))
        self.fields['Company'].empty_label = None


class ResumeeForm(forms.ModelForm):
    class Meta:
        model = Resumee
        exclude = ('owner','status')
        fields = '__all__'



EducationFormSet = inlineformset_factory(Resumee,  Education, exclude=['owner','resumee'], fields='__all__', extra=1,
                    widgets={'degree': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Degree, e.g. Bachelor'}),
                            'major': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Major, e.g. Computer Science'}),
                            'school': forms.TextInput(attrs={'class': 'form-control','placeholder': 'School name, e.g. Massachusetts Institute of Technology'}),
                            'datefrom': forms.TextInput(attrs={'class': 'form-control','placeholder': 'e.g. 2012'}),
                            'dateto': forms.TextInput(attrs={'class': 'form-control','placeholder': 'e.g. 2016'}),
                            'shortdescription': forms.Textarea(attrs={'class': 'form-control','placeholder': 'Short description', 'rows':'3'})
                            })

ExperienceFormSet = inlineformset_factory(Resumee, Experience, exclude=['owner','resumee'], fields='__all__', extra=1,
                    widgets={'companyname': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Company name'}),
                            'position': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Position, e.g. UI/UX Researcher'}),
                            'datefrom': forms.TextInput(attrs={'class': 'form-control','placeholder': 'e.g. 2012'}),
                            'dateto': forms.TextInput(attrs={'class': 'form-control','placeholder': 'e.g. 2016'}),
                            'description': forms.Textarea(attrs={'class': 'summernote-editor'})
                            })

SkillFormSet = inlineformset_factory(Resumee, Skill, exclude=['owner','resumee'], fields='__all__', extra=1,
                    widgets={'skillname': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Skill name, e.g. HTML'}),
                            'proficiency': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Skill proficiency, e.g. 90'}),
                            })

        

JobFinderWeb/api/views.py
from rest_framework import generics, mixins
from JobFinderWeb.models import Job, Provider, Resumee, Seeker, Application
from .serializers import JobSerializer, CompanySerializer, ResumeeSerializer, SeekerSerializer, ApplicationSerializer, NewApplicationSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from JobFinderWeb.models import Company
from rest_framework.mixins import CreateModelMixin
from django.shortcuts import get_object_or_404

from rest_framework.response import Response

from rest_framework import status

from .permissions import IsOwnerOrReadOnly, IsProviderOrReadOnly, IsSeekerOrReadOnly

from django.db.models import Q
from rest_framework.decorators import api_view


class JobApi(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'slug'
    serializer_class = JobSerializer
    permission_classes = [IsOwnerOrReadOnly]

    queryset = Job.objects.all()

    def get_serializer_context(self):
        return {"request": self.request, }


# This allows us to list, search and create
class JobListApi(mixins.CreateModelMixin, generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = JobSerializer

    def get_queryset(self):
        qs = Job.objects.all()
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(jobtitle__icontains=query) |
                Q(shortdescription__icontains=query)
            ).distinct()
        return qs

    def get_serializer_context(self):
        return {"request": self.request}


class NewJobApi(generics.CreateAPIView, generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = JobSerializer
    permission_classes = [IsProviderOrReadOnly, ]

    def get_queryset(self):
        return Job.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class CompanyApi(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'slug'
    serializer_class = CompanySerializer
    permission_classes = [IsOwnerOrReadOnly]
    queryset = Company.objects.all()


class CompanyListApi(generics.ListAPIView):  # List of companies
    lookup_field = 'slug'
    serializer_class = CompanySerializer
    # permission_classes = [IsProviderOrReadOnly,]
    queryset = Company.objects.all()

    # def perform_create(self, serializer):
    #     provider  = get_object_or_404(Provider, identity = self.request.user)
    #     serializer.save(user = self.request.user, provider = provider)

    # def post(self, request, *args, **kwargs):
    #     return self.create(request, *args, **kwargs)


class CompanyJobsApi(generics.ListAPIView):  # Company job lists
    lookup_field = 'slug'
    serializer_class = JobSerializer
    # permission_classes = [IsProviderOrReadOnly,]

    def get_queryset(self):
        qs = Job.objects.all()
        query = self.kwargs.get('slug')
        company = get_object_or_404(Company, slug=query)
        if query is not None:
            qs = qs.filter(Company=company)
        return qs


class CreateCompanyApi(generics.CreateAPIView):
    lookup_field = 'pk'
    serializer_class = CompanySerializer
    permission_classes = [IsProviderOrReadOnly]

    def perform_create(self, serializer):
        provider = get_object_or_404(Provider, identity=self.request.user)
        serializer.save(user=self.request.user, provider=provider)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


@api_view(['GET'])
def GetResumeeListApi(request):
    resumee = Resumee.objects.all()
    serializer = ResumeeSerializer(resumee, many=True)
    return Response(serializer.data)


class GetSeekerResumeeListApi(generics.ListAPIView):
    serializer_class = ResumeeSerializer

    def get_queryset(self, *args, **kwargs):
        query = self.kwargs.get("seeker")
        if query is not None:
            qs = Resumee.objects.filter(owner__username=query)
            return qs


class ResumeeDetailApi(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'slug'
    serializer_class = ResumeeSerializer
    permission_classes = [IsOwnerOrReadOnly, ]
    queryset = Resumee.objects.all()


class CreateResumeeApi(generics.CreateAPIView):
    lookup_field = 'pk'
    serializer_class = ResumeeSerializer
    permission_classes = [IsSeekerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class SeekerListApi(generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = SeekerSerializer
    queryset = Seeker.objects.all()


class SeekerDetailApi(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = SeekerSerializer
    permission_classes = [IsOwnerOrReadOnly, ]
    queryset = Seeker.objects.all()


class ApplicantListApi(generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = ApplicationSerializer
    permission_classes = [IsProviderOrReadOnly]

    def get_queryset(self, *args, **kwargs):
        qs = Application.objects.all()
        companyslug = self.kwargs.get('companyslug')
        if companyslug is not None:
            qs.filter(company__slug=companyslug)
        return qs


class NewApplicationApi(generics.CreateAPIView):
    lookup_field = 'pk'
    serializer_class = ApplicationSerializer
    permission_classes = [IsSeekerOrReadOnly]

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

JobFinderWeb/templates/jobfinderweb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Post a job position or create your online resume by TheJobs!">
    <meta name="keywords" content="">

    <title>{% block title %} {% endblock title %} | JobFinder</title>

    <!-- Styles -->
    <link href= '{% static "css/app.min.css" %}'rel="stylesheet">
    <link href= '{% static "css/thejobs.css" %}'  rel="stylesheet">
    <link href='{% static "custom.css" %}' rel="stylesheet">
    <link href='{% static "vendors/summernote/summernote.css" %}' rel="stylesheet">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href='{% static "img/favicon.ico" %}'>
  </head>

  <body class="nav-on-header smart-nav">

    <!-- Navigation bar -->
    <nav class="navbar">
      <div class="container">

        <!-- Logo -->
        <div class="pull-left">
          <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

          <div class="logo-wrapper">
            <a class="logo" href="index.html"><img src='{% static "img/logo.png" %}' alt="logo"></a>
            <a class="logo-alt" href="index.html"><img src='{% static "img/logo-alt.png" %}' alt="logo-alt"></a>
          </div>

        </div>
        <!-- END Logo --> 

        <!-- User account -->
        {% if user.is_authenticated and user.is_provider %}
        <div class="pull-right">

          <div class="dropdown user-account">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
              <img src='{% static "img/logo-envato.png" %}' alt="avatar">
            </a>

            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href='{% url "JobFinderWeb:jobproviderprofile" username=user.username %}'> {{ user.username }}</a></li>
              <li><a href='{% url "JobFinderWeb:companyjobs" username=user.username %}'>Jobs</a></li>
              {% comment %} <li><a href="user-forget-pass.html">Forget pass</a></li> {% endcomment %}
              <li><a href='{% url "JobFinderWeb:logout" %}'>Log Out</a></li>
            </ul>
          </div>

        </div>
        {% elif user.is_authenticated and user.is_seeker %}
          <div class="pull-right">

          <div class="dropdown user-account">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
              <img src='{% static "img/logo-envato.png" %}' alt="avatar">
            </a>

            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href='{% url "JobFinderWeb:jobseekerprofile" username=user.username %}'> {{ user.username }}</a></li>
              <li><a href='#'>Jobs</a></li>
              {% comment %} <li><a href="user-forget-pass.html">Forget pass</a></li> {% endcomment %}
              <li><a href='{% url "JobFinderWeb:logout" %}'>Log Out</a></li>
            </ul>
          </div>

        </div>
        {% else %}
          <div class="pull-right user-login">
          <a class="btn btn-sm btn-primary" href='{% url "JobFinderWeb:login" %}'>Login</a> or <a href='{% url "JobFinderWeb:register" %}'>register</a>
        </div>
        {% endif %}
        
        <!-- END User account -->

        <!-- Navigation menu -->
        <ul class="nav-menu">
          <li>
            <a class="{% if request.resolver_match.url_name == 'home' %} active {% endif %}" href='{% url 'JobFinderWeb:home' %}'>Home</a>
            {% comment %} <ul>
              <li><a class="active" href="index.html">Version 1</a></li>
              <li><a href="index-2.html">Version 2</a></li>
            </ul> {% endcomment %}
          
          <li> <a class="{% if request.resolver_match.url_name == 'joblist' %} active {% endif %}" href='{% url 'JobFinderWeb:joblist' slug='None' %}'>Jobs</a>
            <ul>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Developer' %}'>Developer</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Information Technology' %}'>IT</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Marketing' %}'>Marketing</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='HealthCare' %}'>HealthCare</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Finance' %}'>Finance</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Designer' %}'>Designer</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Sale' %}'>Sale</a></li>
              <li><a href='{% url 'JobFinderWeb:joblist' slug='Others' %}'>Others</a></li>
            </ul>
          </li>
          </li> <a class="{% if request.resolver_match.url_name == 'companylist' %} active {% endif %}" href='{% url 'JobFinderWeb:companylist' %}'>Companies</a></li>
          </li> <a class="{% if request.resolver_match.url_name == 'home' %} active {% endif %}" href='{% url 'JobFinderWeb:home' %}'>Blog</a></li>
          </li> <a class="{% if request.resolver_match.url_name == 'faq' %} active {% endif %}" href='{% url 'JobFinderWeb:faq' %}'>Faq</a></li>
          </li> <a class="{% if request.resolver_match.url_name == 'about' %} active {% endif %}" href='{% url 'JobFinderWeb:about' %}'>About</a></li>
          </li> <a class="{% if request.resolver_match.url_name == 'contact' %} active {% endif %}" href='{% url 'JobFinderWeb:contact' %}'>Contact</a></li>
          {% comment %} <li>
            <a href="#">Position</a>
            <ul>
              <li><a href="job-list-1.html">Browse jobs - 1</a></li>
              <li><a href="job-list-2.html">Browse jobs - 2</a></li>
              <li><a href="job-list-3.html">Browse jobs - 3</a></li>
              <li><a href="job-detail.html">Job detail</a></li>
              <li><a href="job-apply.html">Apply for job</a></li>
              <li><a href="job-add.html">Post a job</a></li>
              <li><a href="job-manage.html">Manage jobs</a></li>
              <li><a href="job-candidates.html">Candidates</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Resume</a>
            <ul>
              <li><a href="resume-list.html">Browse resumes</a></li>
              <li><a href="resume-detail.html">Resume detail</a></li>
              <li><a href="resume-add.html">Create a resume</a></li>
              <li><a href="resume-manage.html">Manage resumes</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Company</a>
            <ul>
              <li><a href="company-list.html">Browse companies</a></li>
              <li><a href="company-detail.html">Company detail</a></li>
              <li><a href="company-add.html">Create a company</a></li>
              <li><a href="company-manage.html">Manage companies</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Pages</a>
            <ul>
              <li><a href="page-blog.html">Blog</a></li>
              <li><a href="page-post.html">Blog-post</a></li>
              <li><a href="page-about.html">About</a></li>
              <li><a href="page-contact.html">Contact</a></li>
              <li><a href="page-faq.html">FAQ</a></li>
              <li><a href="page-pricing.html">Pricing</a></li>
              <li><a href="page-typography.html">Typography</a></li>
              <li><a href="page-ui-elements.html">UI elements</a></li>
            </ul>
          </li> {% endcomment %}
        </ul>
        <!-- END Navigation menu -->

      </div>
    </nav>
    <!-- END Navigation bar -->
    
{% block content %}


{% endblock content %}
  


    <!-- Site footer -->
    <footer class="site-footer">

      <!-- Top section -->
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">An employment website is a web site that deals specifically with employment or careers. Many employment websites are designed to allow employers to post job requirements for a position to be filled and are commonly known as job boards. Other employment sites offer employer reviews, career and job-search advice, and describe different job descriptions or employers. Through a job website a prospective employee can locate and fill out a job application.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Company</h6>
            <ul class="footer-links">
              <li><a href="page-about.html">About us</a></li>
              <li><a href="page-typography.html">How it works</a></li>
              <li><a href="page-faq.html">Help center</a></li>
              <li><a href="page-typography.html">Privacy policy</a></li>
              <li><a href="page-contact.html">Contact us</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Trendeing jobs</h6>
            <ul class="footer-links">
              <li><a href="job-list.html">Front-end developer</a></li>
              <li><a href="job-list.html">Android developer</a></li>
              <li><a href="job-list.html">iOS developer</a></li>
              <li><a href="job-list.html">Full stack developer</a></li>
              <li><a href="job-list.html">Project administrator</a></li>
            </ul>
          </div>
        </div>

        <hr>
      </div>
      <!-- END Top section -->

      <!-- Bottom section -->
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyrights &copy; 2018 All Rights Reserved by <a href="#">JobFinder</a></p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- END Bottom section -->

    </footer>
    <!-- END Site footer -->


    <!-- Back to top button -->
    <a id="scroll-up" href="#"><i class="ti-angle-up"></i></a>
    <!-- END Back to top button -->

    <!-- Scripts -->
    <script src='{% static "js/app.min.js" %}'></script>
    <script src='{% static "js/thejobs.js" %}'></script>
    <script src='{% static "js/custom.js" %}'></script>
    <script src='{% static "vendors/summernote/summernote.min.js" %}'></script>
    <script src='{% static "js/jquery.formset.js" %}'></script>

    {% block script %}

    {% endblock script %}

    


  </body>
</html>